version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80" # Change 8080 to 8081
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
