version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: challenge3-db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  node-service:
    build:
      context: ./docker/api
    container_name: challenge3-node-service-1
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: challenge3-nginx-1
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-service
